config/routes.rb
Rails.application.routes.draw do
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'posts#index'
    resource :members, only: [:edit, :update]
    get 'members/confirm' => 'members#confirm'
    get 'members/likes' => 'members#likes'
    get "members/mypage" => "members#show"
    get "members/unsubscribe" => "members#unsubscribe"
    patch "members/withdraw" => "members#withdraw"
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    get "search" => "searches#search"
    resources :tags, except: [:index, :show, :edit, :new, :create, :update, :destroy] do
      get 'posts', to: 'posts#search'
    end
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
  end

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root "posts#index"
    resources :posts, only: [:show, :index] do
      resources :comments, only: [:destroy]
    end
    get "comments" => "comments#comments"
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    resources :members, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_many :notifications, dependent: :destroy

  belongs_to :member

  belongs_to :post

  validates :comment, presence: true

  def self.looks(search, word)
    if search == "perfect_matuch"
      @comment = Commnet.where("comment LIKE?", "#{word}")
    elsif search == "forward_match"
      @comment = Comment.where("comment LIKE?", "#{word}%")
    elsif search == "backward_match"
      @comment = Comment.where("comment LIKE?", "%#{word}")
    elsif search == "partial_match"
      @comment = Comment.where("comment LIKE?", "%#{word}%")
    else
      @comment = Comment.all
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def comments
    @comments = Comment.page(params[:page]).per(10)
  end

  def destroy
    @comments = Comment.all
    comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    if comment.destroy
     flash.now[:danger] = "コメントを削除しました"
     render :destroy
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comment_index.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <p class="comment-count-admin">コメント件数:<%= comments.count %></p>
      <% comments.each do |comment| %>
      <div class="comments-index-admin">
        <%= image_tag comment.member.get_profile_image, size: "30x30", class: "rounded-circle" %>
        <%= comment.member.name %>
        <%= comment.created_at.strftime('%Y/%m/%d') %>
        <div class="d-flex">
          <%= comment.comment %>
          <div class="comment-delete">
            <%= link_to "削除", admin_post_comment_path(comment.post, comment), method: :delete, remote: true, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger btn-sm" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-3">
      <%= render 'public/searches/search' %>
    </div>
  </div>
</div>

app/views/admin/comments/comments.html.erb
<div class="comment-index-admin">
  <%= render "admin/comments/comment_index", comments: @comments %>
</div>
<%= paginate @comments %>

app/views/admin/comments/destroy.js.erb
$(".comment-index-admin").html("<%= j(render 'admin/comments/comment_index', comments: @comments) %>")
$('.flash-message').html("<%= j(render 'layouts/flash') %>");