config/routes.rb
Rails.application.routes.draw do
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'posts#index'
    resource :members, only: [:edit, :update]
    get 'members/confirm' => 'members#confirm'
    get 'members/likes' => 'members#likes'
    get "members/mypage" => "members#show"
    get "members/unsubscribe" => "members#unsubscribe"
    patch "members/withdraw" => "members#withdraw"
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    get "search" => "searches#search"
    resources :tags, except: [:index, :show, :edit, :new, :create, :update, :destroy] do
      get 'posts', to: 'posts#search'
    end
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
  end

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root "posts#index"
    resources :posts, only: [:show, :index] do
      resources :comments, only: [:destroy]
    end
    get "comments" => "comments#comments"
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    resources :members, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :member
  has_many :notifications, dependent: :destroy
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_members, through: :likes, source: :member

  has_one_attached :post_image

  enum status:{released: 0, nonreleased: 1}

  validates :location, presence: true
  validates :detail, length: { minimum: 2 }

  scope :latest, -> {order(updated_at: :desc)}
  scope :old, -> {order(updated_at: :asc)}
  scope :like_count, -> { includes(:likes).sort {|a,b| b.likes.size <=> a.likes.size}}

  def get_post_image
    if post_image.attached?
      post_image
    end
  end



  def self.looks(search, word)
    if search == "perfect_matuch"
      @post = Post.where("location LIKE? OR detail LIKE?", "#{word}", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("location LIKE? OR detail LIKE?", "#{word}%", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("location LIKE? OR detail LIKE?", "%#{word}", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("location LIKE? OR detail LIKE?", "%#{word}%", "%#{word}%")
    else
      @post = Post.all
    end
  end


  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'likes'
      return find(Like.group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id))
    when 'dislikes'
      return find(Like.group(:post_id).order(Arel.sql('count(post_id) asc')).pluck(:post_id))
    end
  end

  def liked_by?(member)
    likes.where(member_id: member.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      tag_posts_records = TagPost.where(post_id: self.id)
      tag_posts_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tags = Tag.where(name: tag).first_or_create
      self.tags << inspected_tags
    end

  end

  def create_notification_like!(current_member)
      temp = Notification.where(["visiter_id = ? and visited_id = ? and post_id = ? and action = ? ", current_member.id, member_id, id, "like"])
      if temp.blank?
        notification = current_member.active_notifications.new(
          post_id: id,
          visited_id: member_id,
          action: "like"
        )
        if notification.visiter_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
      end
  end

  def create_notification_comment!(current_member, comment_id)
      temp_ids = Comment.select(:member_id).where(post_id: id).where.not(member_id: current_member.id).distinct
      temp_ids.each do |temp_id|
        save_notification_comment!(current_member, comment_id, temp_id['member_id'])
      end

      save_notification_comment!(current_member, comment_id, member_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_member, comment_id, visited_id)
      notification = current_member.active_notifications.new(
        post_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: "comment"
      )

      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end

      notification.save if notification.valid?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @tag_list = Tag.all
    @posts = Post.where(status: :released).page(params[:page]).per(9)
    if params[:new]
      @posts = Post.latest.page(params[:page]).per(9)
    elsif params[:old]
      @posts = Post.old.page(params[:page]).per(9)
    elsif params[:like]
      posts = Post.like_count
      @posts = Kaminari.paginate_array(posts).page(params[:page]).per(9)
    end
  end

  def show
    @post = Post.find(params[:id])
    @tag_posts = @post.tags
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(10)
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<h2 class="index">投稿一覧</h2>
<div class="container">
  <p class="sort">並び順変更</p>
  <%= link_to '新着順', admin_sort_new_path(new: 'true'), {class: 'sort-link btn btn-secondary btn-sm' "#{'active' if current_page?('/posts/index?new=true')}"} %>
  <%= link_to '古い順', admin_sort_old_path(old: 'true'), {class: 'sort-link btn btn-secondary btn-sm' "#{'active' if current_page?('/posts/index?old=true')}"} %>
  <div class="row row-cols-1 row-cols-md-3 g-3">
    <% @posts.each do |post| %>
      <div class="col">
        <div class="card-index">
          <%= link_to admin_post_path(post.id) do %>
            <%= image_tag post.get_post_image, width: "100%", height: "100%" %>
          <% end %>
          <strong>撮影地</strong>：<%= post.location %><br>
          <strong>投稿者コメント</strong>：<%= post.detail %><br>
          <div class="d-flex">
            <i class="fas fa-tag"></i>
            <%= post.tags.map(&:name).join(',') %>
            <div class="comment">
              <i class="fas fa-comment-dots"></i>
              <%= link_to admin_post_path(post.id) do %>
                <%= "#{post.comments.count}" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<h3 class="show">投稿詳細</h3>
<div class="container">
  <div class="row">
    <%= render 'public/posts/post_show', post: @post, tag_posts: @tag_posts %>
    <div class="col-4">
      <div id="comment-area">
        <%= render "public/comments/index", post: @post, comments: @comments %>
      </div>
      <%= paginate @comments %>
    </div>
  </div>
</div>