config/routes.rb
Rails.application.routes.draw do
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    root to: 'posts#index'
    resource :members, only: [:edit, :update]
    get 'members/confirm' => 'members#confirm'
    get 'members/likes' => 'members#likes'
    get "members/mypage" => "members#show"
    get "members/unsubscribe" => "members#unsubscribe"
    patch "members/withdraw" => "members#withdraw"
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    get "search" => "searches#search"
    resources :tags, except: [:index, :show, :edit, :new, :create, :update, :destroy] do
      get 'posts', to: 'posts#search'
    end
    resources :notifications, only: [:index] do
      collection do
        delete 'destroy_all'
      end
    end
  end

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    root "posts#index"
    resources :posts, only: [:show, :index] do
      resources :comments, only: [:destroy]
    end
    get "comments" => "comments#comments"
    get "sort_new" => "posts#index"
    get "sort_old" => "posts#index"
    get "sort_like" => "posts#index"
    resources :members, only: [:index, :show, :update]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-primary">
  <p class="footer-text">© Photrain(フォトレイン)</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <div class="navbar-brand" style="padding-bottom: 15px;">
    <% if member_signed_in? %>
      <%= link_to root_path do %>
        <%= image_tag ('logo.png'), width:'100%', height:"100%" %>
      <% end %>
    <% else %>
      <%= link_to admin_root_path do %>
        <%= image_tag ('logo.png'), width:'100%', height:"100%" %>
      <% end %>
    <% end %>
    </div>
    <div>
      <ul class="navbar-nav ml-auto", style="font-family: Hannotate SC;">
        <% if member_signed_in? %>
          <li>
            <%= link_to members_mypage_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-house-user"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-plus"></i> 新規投稿
            <% end %>
          </li>
          <li>
            <%= link_to notifications_path, class: 'btn btn-outline-dark' do %>
              <% if unchecked_notifications.any? %>
                <span class="fa-stack fa-lg">
                  <i class="fas fa-bell fa-stack-1x" style="color: green;"></i>
                  <i class="fa fa-circle fa-stack-1x n-circle" style="color: gold;"></i>
                </span>通知
              <% else %>
                <i class="fas fa-bell"></i>通知
              <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to members_likes_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-bookmark"></i> いいね
            <% end %>
          </li>
          <li>
            <%= link_to destroy_member_session_path, method: :delete, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to admin_members_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-users"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_posts_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-list-alt"></i>投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_comments_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-list-alt"></i>コメント一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_member_registration_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_member_session_path, class: 'btn btn-outline-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="flash-message">
      <%= render partial: 'layouts/flash' %>
    </div>
    <%= yield %>
    <footer class="footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>